server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/transactional-coroutine
        username: root
        password: 1234
        hikari:
            register-mbeans: true
            pool-name: hikari

    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
                show_sql: false
                use_sql_comments: false
        open-in-view: false

logging:
    level:
        org:
            hibernate:
                sql: info
        com.zaxxer.HikariConfig: debug
        com.zaxxer.hikari: trace

