server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/transactional-coroutine
        username: root
        password: 1234

    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
        properties:
          hibernate:
              format_sql: false
              show_sql: false
              use_sql_comments: false

logging:
    level:
      org:
          hibernate:
              sql: info
